# Generated by Django 4.1.7 on 2023-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=50)),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sage', models.IntegerField()),
                ('saddress', models.TextField()),
            ],
        ),
    ]
